### ISSUE TITLE
JavaScript Anki deck is out of date

### ISSUE THREAD

**Issue by PhinonceLabs** [envico801/javascript-interview-questions#1]
Hi,

I really appreciate your effort in creating the Anki deck for JavaScript interviews. However, even the first card on how to create objects is quite outdated (e.g. using 'var' instead of 'const' and referencing ES6). More from 4o:

	1.	var Usage: Many code examples use var to declare variables, which is generally discouraged in modern JavaScript. Using let or const is considered best practice because they have block scope and avoid the pitfalls of var’s function scope and hoisting behavior.
	2.	Handling Asynchronous Errors with try...catch: In one example, an error is thrown within a setTimeout function, but the catch block is outside the asynchronous function. A better approach is to either use async/await syntax within an async function or Promise chaining, as try...catch does not handle asynchronous errors effectively outside the asynchronous function.
	3.	Direct Use of Promise.all with Mixed Fulfillment and Rejection: A code example uses Promise.all with promises that can both fulfill and reject, which causes an error on any rejection. Instead, Promise.allSettled is more robust when handling an array of promises that may have mixed results, as it ensures all promises complete before returning results.
	4.	Object Comparisons Using ===: An example tries to compare two objects directly, which results in a false comparison due to the nature of object references. A more robust practice for object comparison is using utility functions or libraries like lodash for deep equality checks, as comparing references directly often causes issues.
	5.     Manual Random HEX Color Generation: The deck contains an example for generating a random HEX color manually using an array and Math.random(). However, a simpler approach would use bitwise operations to randomize a number and convert it to HEX format, such as: const randomColor = `#${Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, "0")}`;
	6. Arrow Functions and this Binding: Examples of this binding using arrow functions within objects are included, but they could be better explained with a caution against arrow functions in certain scenarios, such as methods in ES6 classes where this binding may be unintended.
	7.	Manual Sorting in Array.sort(): The deck suggests passing a comparison function to Array.sort(), but lacks a caution that sort methods can be unstable in some environments and should not be assumed to work identically in all cases, especially in edge cases with extensive data.

**Comment by envico801** [comment]
Hi @PhinonceLabs, yes, many of the cards are outdated. This is because the cards are created from a 6 year old repository: [sudheerj/javascript-interview-questions](https://github.com/sudheerj/javascript-interview-questions). And the deck I created is a conversion from that repository to Anki's cards.

The problem with that repository, is that besides having old examples, it also has user errors or indentation problems, this is because there are multiple contributors and there is no style guide like prettier for example. And all possible problems in the main repository are transferred to the anki cards.

The solution I am using is to write in the cards in my own words what would be the correct answer. For example:

![example card](https://github.com/user-attachments/assets/865b3717-b3d6-4090-8018-0771c91ff7e3)

This way I can learn the topics in a better way. You can even use tools like [ChatGPT](https://chat.openai.com/) or [Claude.ai](https://claude.ai/) (I personally prefer the latter, it is better for programming topics) to explain topics that you don't know or that you think are wrongly explained in the Anki cards.

And also it never hurts to learn how is the old javascript syntax, who knows, maybe in a next job you will have to work on legacy code that uses that syntax 😉

**Comment by PhinonceLabs** [comment]
I like the front side topics so I'm just updating the backsides with AI. I have no intention of working as a dev for another org, thankfully.

**Comment by envico801** [comment]
Thanks for the feedback, sorry if I can't solve your problem 100%, for now I will close the issue but feel free to open a new one whenever you want. cheers!
